name: Demo Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 23f1002121@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      
      - name: Run tests
        run: |
          echo "Running some tests"
          date
